// <auto-generated />
using System;
using DocumentService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentService.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    [Migration("20261004060403_AddBusinessCatalogs")]
    partial class AddBusinessCatalogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("document")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentService.BusinessCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Group", "Code")
                        .IsUnique();

                    b.ToTable("BusinessCatalogEntries", "document");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000100000001"),
                            Code = "HL",
                            Group = "companies",
                            IsActive = true,
                            Name = "Hoàng Long",
                            SortOrder = 1,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000100000002"),
                            Code = "HV",
                            Group = "companies",
                            IsActive = true,
                            Name = "Hoàn Vũ",
                            SortOrder = 2,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000100000003"),
                            Code = "HLHV",
                            Group = "companies",
                            IsActive = true,
                            Name = "Hoàng Long Hoàn Vũ",
                            SortOrder = 3,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000200000001"),
                            Code = "FAX",
                            Group = "methods",
                            IsActive = true,
                            Name = "Fax",
                            SortOrder = 1,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000200000002"),
                            Code = "COURIER",
                            Group = "methods",
                            IsActive = true,
                            Name = "Courier",
                            SortOrder = 2,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000200000003"),
                            Code = "EMAIL",
                            Group = "methods",
                            IsActive = true,
                            Name = "eMail",
                            SortOrder = 3,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000200000004"),
                            Code = "HAND_DELIVER",
                            Group = "methods",
                            IsActive = true,
                            Name = "Pick-up/Hand-Deliver",
                            SortOrder = 4,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000200000005"),
                            Code = "EMAIL_FAX",
                            Group = "methods",
                            IsActive = true,
                            Name = "Email & Fax",
                            SortOrder = 5,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000300000001"),
                            Code = "LETTER",
                            Group = "documentTypes",
                            IsActive = true,
                            Name = "Letter",
                            SortOrder = 1,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000300000002"),
                            Code = "NOTIFICATION",
                            Group = "documentTypes",
                            IsActive = true,
                            Name = "Notification",
                            SortOrder = 2,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000300000003"),
                            Code = "ANNOUNCEMENT",
                            Group = "documentTypes",
                            IsActive = true,
                            Name = "Announcement",
                            SortOrder = 3,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000300000004"),
                            Code = "APPROVAL_REQUEST",
                            Group = "documentTypes",
                            IsActive = true,
                            Name = "Approval / Request",
                            SortOrder = 4,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000300000005"),
                            Code = "INVITATION",
                            Group = "documentTypes",
                            IsActive = true,
                            Name = "Invitation",
                            SortOrder = 5,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000300000006"),
                            Code = "STATEMENT",
                            Group = "documentTypes",
                            IsActive = true,
                            Name = "Statement",
                            SortOrder = 6,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000400000001"),
                            Code = "MEMO",
                            Group = "internalTypes",
                            IsActive = true,
                            Name = "Inter-Office Memo",
                            SortOrder = 1,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000400000002"),
                            Code = "REPORT",
                            Group = "internalTypes",
                            IsActive = true,
                            Name = "Report",
                            SortOrder = 2,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000400000003"),
                            Code = "STATEMENT",
                            Group = "internalTypes",
                            IsActive = true,
                            Name = "Statement",
                            SortOrder = 3,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000400000004"),
                            Code = "PURCHASE_REQUEST",
                            Group = "internalTypes",
                            IsActive = true,
                            Name = "Purchase Request",
                            SortOrder = 4,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000400000005"),
                            Code = "OTHERS",
                            Group = "internalTypes",
                            IsActive = true,
                            Name = "Others",
                            SortOrder = 5,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000500000001"),
                            Code = "Normal",
                            Group = "sensitivity",
                            IsActive = true,
                            Name = "Normal",
                            SortOrder = 1,
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000500000002"),
                            Code = "Confidential",
                            Group = "sensitivity",
                            IsActive = true,
                            Name = "Confidential",
                            SortOrder = 2,
                            Version = 1L
                        });
                });

            modelBuilder.Entity("DocumentService.CatalogAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("CatalogAuditEvents", "document");
                });

            modelBuilder.Entity("DocumentService.DistributionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Initial")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("MappingState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId")
                        .IsUnique();

                    b.ToTable("DistributionTargets", "document");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000001"),
                            Initial = "MGM",
                            IsActive = true,
                            LegacyId = 1,
                            MappingState = "Pending",
                            Name = "Management",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000002"),
                            Initial = "PRD",
                            IsActive = true,
                            LegacyId = 2,
                            MappingState = "Pending",
                            Name = "Production",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000003"),
                            Initial = "HSE",
                            IsActive = true,
                            LegacyId = 3,
                            MappingState = "Pending",
                            Name = "HSE",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000004"),
                            Initial = "PRJ",
                            IsActive = true,
                            LegacyId = 4,
                            MappingState = "Pending",
                            Name = "Project",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000005"),
                            Initial = "SUB",
                            IsActive = true,
                            LegacyId = 5,
                            MappingState = "Pending",
                            Name = "Subsurface",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000006"),
                            Initial = "FIN",
                            IsActive = true,
                            LegacyId = 6,
                            MappingState = "Pending",
                            Name = "Finance",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000007"),
                            Initial = "ADM",
                            IsActive = true,
                            LegacyId = 7,
                            MappingState = "Pending",
                            Name = "Administration",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000008"),
                            Initial = "C&P",
                            IsActive = true,
                            LegacyId = 8,
                            MappingState = "Pending",
                            Name = "C&P",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000009"),
                            Initial = "DRI",
                            IsActive = true,
                            LegacyId = 9,
                            MappingState = "Pending",
                            Name = "Drilling",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000010"),
                            IsActive = true,
                            LegacyId = 10,
                            MappingState = "Pending",
                            Name = "HLHV Partners",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000011"),
                            IsActive = true,
                            LegacyId = 11,
                            MappingState = "Pending",
                            Name = "Secretary List",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000012"),
                            IsActive = true,
                            LegacyId = 12,
                            MappingState = "Pending",
                            Name = "VT Shore Base",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000013"),
                            IsActive = true,
                            LegacyId = 13,
                            MappingState = "Pending",
                            Name = "HLHV Members",
                            Version = 1L
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-4000-8000-000600000014"),
                            Initial = "HLHVM",
                            IsActive = true,
                            LegacyId = 14,
                            MappingState = "Pending",
                            Name = "HLHV Managers",
                            Version = 1L
                        });
                });

            modelBuilder.Entity("DocumentService.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DistributedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SenderDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceMessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.HasIndex("SourceMessageId")
                        .IsUnique()
                        .HasFilter("[SourceMessageId] IS NOT NULL");

                    b.HasIndex("DocType", "Status");

                    b.ToTable("Documents", "document");
                });

            modelBuilder.Entity("DocumentService.DocumentAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentAttachments", "document");
                });

            modelBuilder.Entity("DocumentService.DocumentDepartmentAccess", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId", "DepartmentId");

                    b.ToTable("DocumentDepartmentAccess", "document");
                });

            modelBuilder.Entity("DocumentService.DocumentNumberCounter", b =>
                {
                    b.Property<string>("DocType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.HasKey("DocType", "Year");

                    b.ToTable("DocumentNumberCounters", "document");
                });

            modelBuilder.Entity("DocumentService.DocumentStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentStatusHistory", "document");
                });

            modelBuilder.Entity("DocumentService.DocumentAttachment", b =>
                {
                    b.HasOne("DocumentService.Document", "Document")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentService.DocumentDepartmentAccess", b =>
                {
                    b.HasOne("DocumentService.Document", "Document")
                        .WithMany("DepartmentAccesses")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentService.DocumentStatusHistory", b =>
                {
                    b.HasOne("DocumentService.Document", "Document")
                        .WithMany("StatusHistories")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentService.Document", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("DepartmentAccesses");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
