import gzip
import re
import uuid
import json
from datetime import datetime

DUMP_PATH = r"D:\TRONGNGUYEN_HK7\Du_An_Quan_Ly_Cong_Van\SELETON\DAS-Collaboration\DAS_Thuong_Mai\DAS.sql.gz"
OUTPUT_PATH = r"D:\TRONGNGUYEN_HK7\Du_An_Quan_Ly_Cong_Van\SELETON\DAS-Collaboration\scripts\migrated_partners.sql"

def parse_sql_values(values_str):
    """
    Hàm này dùng để parse thủ công các giá trị từ chuỗi (A, B, C), (D, E, F) của MariaDB dump.
    Do tính chất phức tạp của escaped string trong SQL dump, ta nên dùng regex cẩn thận.
    Để nhanh gọn, với mục đích chuẩn hóa dữ liệu cũ, ta tách theo bộ (...).
    """
    # Regex này chỉ mang tính tương đối cho các dump đơn giản. Thực tế cần dùng parser chuyên dụng nếu data phức tạp.
    pattern = re.compile(r"\((.*?)\)(?:,|;)", re.DOTALL)
    return pattern.findall(values_str)

def clean_string(val):
    if val == "NULL": return "NULL"
    if val.startswith("'") and val.endswith("'"):
        return val[1:-1].replace("''", "'").replace("\\'", "'").strip()
    return val.strip()

def main():
    print(f"[*] Reading dump from {DUMP_PATH}...")
    
    insert_prefix = "INSERT INTO `partners`"
    
    partners_data = ""
    with gzip.open(DUMP_PATH, 'rt', encoding='utf-8', errors='ignore') as f:
        in_insert = False
        for line in f:
            if line.startswith(insert_prefix):
                in_insert = True
                partners_data += line.replace(insert_prefix, "").strip()
            elif in_insert:
                partners_data += line.strip()
                if line.strip().endswith(';'):
                    break

    if not partners_data:
        print("[!] Không tìm thấy dữ liệu INSERT INTO `partners`")
        return

    # Lọc bỏ đoạn `(...) VALUES `
    if "VALUES" in partners_data:
        partners_data = partners_data.split("VALUES")[1].strip()

    raw_rows = parse_sql_values(partners_data)
    print(f"[*] Tìm thấy {len(raw_rows)} đối tác trong file dump.")

    out_lines = []
    out_lines.append("-- SQL Migration Script for Partner Service")
    out_lines.append("-- Generated by Antigravity AI\n")

    for row in raw_rows:
        # Tách các cột. SQL dump dùng dấu phẩy, nhưng cẩn thận dấu phẩy trong chuỗi '...'
        # Một cách đơn giản là dùng csv reader với quotechar="'"
        import csv
        from io import StringIO
        
        # Do MariaDB escape là \' thay vì '', ta cần xử lý
        clean_row = row.replace("\\'", "''") 
        reader = csv.reader(StringIO(clean_row), quotechar="'", skipinitialspace=True)
        try:
            cols = next(reader)
        except StopIteration:
            continue
            
        if len(cols) < 20:
            continue

        legacy_id = cols[0]
        name = clean_string(cols[1])
        name2 = clean_string(cols[2])
        # tax_code = cols[4]
        tax_code = clean_string(cols[4])
        contact = clean_string(cols[5])
        email = clean_string(cols[6])
        phone = clean_string(cols[7])
        fax = clean_string(cols[8])
        
        address1 = clean_string(cols[9])
        address2 = clean_string(cols[10])
        address3 = clean_string(cols[11])
        
        # Gộp địa chỉ
        addr_parts = [a for a in [address1, address2, address3] if a and a != 'NULL']
        full_address = ", ".join(addr_parts)
        if not full_address: full_address = "NULL"
        else: full_address = f"'{full_address}'"
        
        # Chuẩn hóa số điện thoại (gộp phone và fax nếu cần)
        contact_info = []
        if fax != 'NULL': contact_info.append(f"Fax: {fax}")
        contact_info_str = " | ".join(contact_info)
        if not contact_info_str: contact_info_str = "NULL"
        else: contact_info_str = f"'{contact_info_str}'"
        
        name_sql = f"'{name}'" if name != 'NULL' else "NULL"
        name2_sql = f"'{name2}'" if name2 != 'NULL' else "NULL"
        tax_code_sql = f"'{tax_code}'" if tax_code != 'NULL' else "NULL"
        contact_sql = f"'{contact}'" if contact != 'NULL' else "NULL"
        email_sql = f"'{email}'" if email != 'NULL' else "NULL"
        phone_sql = f"'{phone}'" if phone != 'NULL' else "NULL"

        # UUID mới cho Partner
        new_id = str(uuid.uuid4())
        
        # Mapping sang schema mới của PartnerDbContext
        # Id, FullName, ShortName, NormalizedShortName, NormalizedTaxCode, ContactPerson, ContactInformation, Version, EntityType, Email, Phone, Address, TaxCode, IsActive, IsDeleted, CreatedAt, CreatedByUserId
        
        normalized_short = f"UPPER({name2_sql})" if name2 != 'NULL' else "NULL"
        normalized_tax = f"UPPER({tax_code_sql})" if tax_code != 'NULL' else "NULL"
        
        insert_sql = f"""INSERT INTO partner.Partners 
(Id, FullName, ShortName, NormalizedShortName, NormalizedTaxCode, ContactPerson, ContactInformation, Version, EntityType, Email, Phone, Address, TaxCode, IsActive, IsDeleted, CreatedAt, CreatedByUserId)
VALUES 
('{new_id}', {name_sql}, {name2_sql}, {normalized_short}, {normalized_tax}, {contact_sql}, {contact_info_str}, 1, 'Both', {email_sql}, {phone_sql}, {full_address}, {tax_code_sql}, 1, 0, GETUTCDATE(), '00000000-0000-0000-0000-000000000000');
"""
        out_lines.append(insert_sql)

    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write("\n".join(out_lines))
        
    print(f"[*] Done! Đã xuất file SQL sang {OUTPUT_PATH}")

if __name__ == "__main__":
    main()
